# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.7-dev"
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U coveralls
  - pip install -e .

# Command to run tests, e.g. python setup.py test
script:
  - python setup.py test
  - coverage run setup.py test
  - coverage report -m

after_success:
  - coveralls
